version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  pgdata: {}

networks:
  postgres:
    driver: bridge